export default {
  SET_PROFILES: 'SET_PROFILES',
  SET_ACTIVE_PROFILE: 'SET_ACTIVE_PROFILE',
  SAVE_FIRST_REVIEW: 'SAVE_FIRST_REVIEW',
  SAVE_NOTE: 'SAVE_NOTE',
  SAVE_NEW_SESSION: 'SAVE_NEW_SESSION',
  SET_BILLINGS: 'SET_BILLINGS',
};
